//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.Idem"/> </summary
    public sealed class IdemClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public IdemClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "Idem";
            }
        }
        
        /// <summary>
        /// Call the TestMethod method on the Idem microservice
        /// <see cref="Beamable.Microservices.Idem.TestMethod"/>
        /// </summary>
        public Beamable.Common.Promise<int> TestMethod()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<int>("Idem", "TestMethod", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersIdemClient
    {
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForIdemClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<IdemClient>();
        }
        
        public static IdemClient Idem(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<IdemClient>();
        }
    }
}
